### ISSUE TITLE
Migrate to 2.32.x

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-app-skeleton#10]
- @SferaDev to upload the skeleton to a 2.32 branch
- Upgrade libs and adapt code:
   - lodash (ts)
   - material-ui
   - react
- Review routing libs with hooks (`navi`?)
- Discuss test infrastructure:
   - Integration: cypress ha funcionado, pero escribir el código de tests a mano ha resultado muy costoso.
        - Estudiar: https://github.com/oscartavarez/cypress-recorder -> JS copy&paste .spec.js
        - Valorar si en vez de invertir tiempo en el setup/tearDown manual de datos, levantar server dhis2 on-the-fly (con d2-docker con Amazon. Ver integración con Travis).
        - More robust test cypress (retries? HTTP 500?)
  - Unit: https://github.com/testing-library/react-testing-library
  - Más tests unitarios para métodos com lógico compleja.
  - React components: https://github.com/slorber/react-async-hook
- Comments (specially on header of files, tricky funcions and whenever possible, public methods. Which syntax, free?).
- Activate dependabot ?
- Study user-friendly reporting (for controlled and uncontrolled errors,  [SEND] email).
- package.json:  ~ OR ^?
- db-api: TS library for Dhis2 api (metadata, values, ....). Auto-generated models + inferred types, autocancellable, caching.
- Investigate tree shaking (react, lodash -> singleton require), automatic tools? use peerDependencies more.
- Investigate https://www.netlify.com/
- d2-ui-components open issues
   - Refactor Object Table (EyeSeeTea/d2-ui-components#62) (EyeSeeTea/d2-ui-components#38)
   - Remove d2 dependency OrgUnit Selector and multiselector (EyeSeeTea/d2-ui-components#63)
   - Object table visual bug (EyeSeeTea/d2-ui-components#40)

**Comment by adrianq** [comment]
- [ ] @SferaDev to upload the skeleton to a 2.32 branch
- [ ] Upgrade libs and adapt code:
   - lodash (ts)
   - material-ui
   - react
   - typescript
- [ ] Test infrastructure:
  - Check cypress is integrated
  - Component Unit: https://github.com/testing-library/react-testing-library
- [ ] Generic React Data Components: https://github.com/slorber/react-async-hook
- [ ] Get d2 vaccination infrastructure (metadata GET)

Later:
- [ ] d2-api: TS library for Dhis2 api (metadata, values, ....). Auto-generated models + inferred types

Future:
- d2-api: autocancellable, caching.
- d2-ui-components open issues
   - Refactor Object Table (EyeSeeTea/d2-ui-components#62) (EyeSeeTea/d2-ui-components#38)
   - Remove d2 dependency OrgUnit Selector and multiselector (EyeSeeTea/d2-ui-components#63)
   - Object table visual bug (EyeSeeTea/d2-ui-components#40)
- Review routing libs with hooks (`navi`?)
- Test Integration: cypress ha funcionado, pero escribir el código de tests a mano ha resultado muy costoso.
   - Estudiar: https://github.com/oscartavarez/cypress-recorder -> JS copy&paste .spec.js
   - Valorar si en vez de invertir tiempo en el setup/tearDown manual de datos, levantar server dhis2 on-the-fly (con d2-docker con Amazon. Ver integración con Travis).
    - More robust test cypress (retries? HTTP 500?)
- Activate dependabot ?
- Study user-friendly reporting (for controlled and uncontrolled errors,  [SEND] email).
- Investigate tree shaking (react, lodash -> singleton require), automatic tools? use peerDependencies more.
- Investigate https://www.netlify.com/

**Comment by SferaDev** [comment]
I have a first attempt on the d2-api road locally (both a TS wrapper for calls with caching, retrying on network failure and cancelation and the dynamic type generation from the schemas).

I will ask @tokland for the dynamic type referencing he did so we can join it together, maybe on a new repository.

**Comment by adrianq** [comment]
Closing this. All the relevant tasks have been moved to individual issues
