### ISSUE TITLE
Polish Skeleton

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dhis2-app-skeleton#2]
- [x] Pass Root.component from notifications-app
- [x] Add snackbar feedback infrastructure
- [x] Check jest/enzyme
- [x] Pass integration infrastructure from notifications-app
- [x] Add Config files (app-config.json from user-extended-app)
- [x] Add Feedback (bottom-right)
- [x] Add Sharing (bottom-right)
- [x] get EST Travis tokens (@adrianq)
- [x] Setup travis (.travis.yml)

**Comment by adrianq** [comment]
Activated repos in travis (skeleton and notifications). No token is needed unless we need to pass any variable (see https://docs.travis-ci.com/user/encryption-keys/) For now this should be enough

**Comment by tokland** [comment]
Done: https://github.com/EyeSeeTea/dhis2-app-skeleton/pull/1
