### ISSUE TITLE
Investigate use of UI

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dhis2-app-skeleton#4]
maps-app has starting using the " Re-work of d2-ui ", ui (https://github.com/dhis2/ui). See:

https://github.com/dhis2/maps-app/commit/e8a3a9388a40d4ce070ed7871baf20866cd1729d

For now, only for a global App wrapper and the Header Bar.

**Comment by adrianq** [comment]
This is more a sort of continuous task that we keep doing every now and then
